[production]
redis_url = "redis://localhost:6379"
secrets_file_path = "/home/prakhar/.securum_exire/credentials.json"
listening_port_address = "0.0.0.0:10012"
signal_server_address = "127.0.0.1:10000"
